import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import date

from dotenv import load_dotenv

from db import get_connection, init_db, get_new_matches, mark_notified

load_dotenv()

PREVIEW_FILE = "email_preview.html"


def build_html(jobs: list[dict]) -> str:
    rows = ""
    for job in jobs:
        rows += f"""
        <tr>
            <td><a href="{job['url']}" style="color:#1a73e8;text-decoration:none;">{job['title']}</a></td>
            <td>{job['company']}</td>
            <td style="color:#888;font-size:12px;">{job.get('source', '')}</td>
            <td style="text-align:center;font-weight:bold;color:#1a73e8;">{job['cv_score']}</td>
            <td style="text-align:center;font-weight:bold;color:#0f9d58;">{job['job_score']}</td>
            <td style="color:#555;">{job['rationale_cv']}</td>
            <td style="color:#555;">{job['rationale_job']}</td>
        </tr>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Job Finder — Daily Digest</title>
  <style>
    body {{ font-family: Arial, sans-serif; background: #f5f5f5; margin: 0; padding: 20px; color: #333; }}
    .container {{ max-width: 900px; margin: 0 auto; background: #fff; border-radius: 8px;
                  box-shadow: 0 2px 8px rgba(0,0,0,0.1); overflow: hidden; }}
    .header {{ background: #1a73e8; color: #fff; padding: 24px 32px; }}
    .header h1 {{ margin: 0; font-size: 22px; }}
    .header p {{ margin: 6px 0 0; opacity: 0.85; font-size: 14px; }}
    .body {{ padding: 24px 32px; }}
    table {{ width: 100%; border-collapse: collapse; font-size: 14px; }}
    th {{ background: #f0f4ff; text-align: left; padding: 10px 12px;
          border-bottom: 2px solid #d0d9f0; color: #444; font-size: 12px;
          text-transform: uppercase; letter-spacing: 0.5px; }}
    td {{ padding: 10px 12px; border-bottom: 1px solid #eee; vertical-align: top; }}
    tr:last-child td {{ border-bottom: none; }}
    tr:hover td {{ background: #f8f9ff; }}
    .footer {{ padding: 16px 32px; font-size: 12px; color: #aaa;
               border-top: 1px solid #eee; text-align: center; }}
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Job Finder — Daily Digest</h1>
      <p>{len(jobs)} high-match role{'s' if len(jobs) != 1 else ''} found &nbsp;·&nbsp; {date.today().strftime('%B %d, %Y')}</p>
    </div>
    <div class="body">
      <table>
        <thead>
          <tr>
            <th>Position</th>
            <th>Company</th>
            <th>Source</th>
            <th style="text-align:center;">CV Score</th>
            <th style="text-align:center;">Job Score</th>
            <th>CV Screen Rationale</th>
            <th>Job Fit Rationale</th>
          </tr>
        </thead>
        <tbody>{rows}
        </tbody>
      </table>
    </div>
    <div class="footer">
      Generated by Job Finder · Scores are 0–100 (CV Screen = likelihood of passing HR filter, Job Score = realistic chance of offer)
    </div>
  </div>
</body>
</html>"""


def send_email(html: str) -> None:
    user = os.environ["GMAIL_USER"]
    password = os.environ["GMAIL_APP_PASSWORD"]
    recipient = os.environ["GMAIL_TO"]

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Job Finder — {date.today().strftime('%b %d')} Digest"
    msg["From"] = user
    msg["To"] = recipient
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(user, password)
        server.sendmail(user, recipient, msg.as_string())

    print(f"Email sent to {recipient}")


def run_notifier(conn) -> None:
    jobs = get_new_matches(conn)
    if not jobs:
        print("No new high-match jobs to notify.")
        return

    html = build_html(jobs)
    mock = os.getenv("MOCK_EMAIL", "false").lower() == "true"

    if mock:
        with open(PREVIEW_FILE, "w", encoding="utf-8") as f:
            f.write(html)
        print(f"Mock mode: email preview written to {PREVIEW_FILE}")
    else:
        send_email(html)

    for job in jobs:
        mark_notified(conn, job["url"])


if __name__ == "__main__":
    conn = get_connection()
    init_db(conn)

    # Insert dummy data so we can preview the email without scrapers/matcher
    from db import insert_job, update_match

    dummy_jobs = [
        {
            "title": "Algorithm Engineer — RADAR",
            "company": "Elbit Systems",
            "source": "Elbit Systems",
            "url": "https://example.com/job/elbit-radar",
            "description": "Develop detection and tracking algorithms for airborne RADAR systems.",
            "cv_score": 91,
            "job_score": 85,
            "rationale_cv": "Candidate's RADAR algorithm work and EE degree are a direct match.",
            "rationale_job": "Strong fit; military background may require security clearance verification.",
        },
        {
            "title": "Signal Processing Engineer",
            "company": "Mobileye",
            "source": "Mobileye",
            "url": "https://example.com/job/mobileye-dsp",
            "description": "Design DSP pipelines for autonomous driving sensor fusion.",
            "cv_score": 80,
            "job_score": 76,
            "rationale_cv": "Signal processing expertise is well-aligned; ADAS domain is new.",
            "rationale_job": "Transferable skills but lacks autonomous driving experience.",
        },
        {
            "title": "Acoustic Systems Engineer",
            "company": "Rafael Advanced Defense Systems",
            "source": "Drushim",
            "url": "https://example.com/job/rafael-acoustic",
            "description": "R&D of underwater acoustic detection and classification systems.",
            "cv_score": 95,
            "job_score": 90,
            "rationale_cv": "Exact match — SONAR expertise, beamforming, threat classification.",
            "rationale_job": "Exceptional fit across all dimensions; strong likelihood of offer.",
        },
    ]

    for j in dummy_jobs:
        insert_job(conn, j["title"], j["company"], j["url"], j["description"], source=j["source"])
        update_match(conn, j["url"], j["cv_score"], j["job_score"], j["rationale_cv"], j["rationale_job"])

    run_notifier(conn)
    conn.close()
